GOOGLE_MAPS_API_KEY = ENV["GOOGLE_MAPS_API_KEY"]
FLICKR_CLIENT_ID = ENV['FLICKR_CLIENT_ID']
FLICKR_SECRET_ID = ENV['FLICKR_SECRET_ID']

FlickRaw.api_key = FLICKR_CLIENT_ID
FlickRaw.shared_secret = FLICKR_SECRET_ID